In [1]:
import numpy as np

In [5]:
A=[[1,2,3],[4,5,6],[7,8,9]]
print(np.sum(A))

45


In [7]:
print(np.sum(A,axis=0))
print(np.sum(A,axis=0).shape)

[12 15 18]
(3,)


In [9]:
print(np.sum(A,axis=1))
print(np.sum(A,axis=1).shape)

[ 6 15 24]
(3,)


In [11]:
print(np.sum(A,axis=0,keepdims=True))
print(np.sum(A,axis=0,keepdims=True).shape)

[[12 15 18]]
(1, 3)


In [13]:
print(np.sum(A,axis=1,keepdims=True))
print(np.sum(A,axis=1,keepdims=True).shape)

[[ 6]
 [15]
 [24]]
(3, 1)
