In [3]:
import numpy as np
inputs=[0,2,-1,3.3,-2.7,1.1,2.2,-100]
output = np.maximum(0, inputs)
print(output)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [4]:
class Activation_Relu:
    def forward(self , inputs):
        self.output = np.maximum(0, inputs)

In [5]:
inputs=[[1,2,3,2.5],
        [2.,5.,-1.,2],
        [-1.5,2.7,3.3,-0.8]]
exp_values=np.exp(inputs-np.max(inputs, axis=1, keepdims=True))
probs=exp_values/np.sum(exp_values, axis=1 , keepdims=True)
print(probs)
np.sum(probs, axis=1)

[[0.06414769 0.17437149 0.47399085 0.28748998]
 [0.04517666 0.90739747 0.00224921 0.04517666]
 [0.00522984 0.34875873 0.63547983 0.0105316 ]]


array([1., 1., 1.])

In [6]:
class Activation_Softmax:
    def forward(self , inputs):
        exp_values=np.exp(inputs-np.max(inputs, axis=1 , keepdims=True))
        probabilities=exp_values/np.sum(exp_values, axis=1 , keepdims=True)
        self.output=probabilities

*CROSS ENTROPY LOSS*



In [9]:
softmax_outputs=np.array([[0.7,0.1,0.2],
                          [0.1,0.5,0.4],
                          [0.02,0.9,0.08]])
class_targets=[0,1,1]
print(softmax_outputs[[0,1,2], class_targets])

[0.7 0.5 0.9]


In [17]:
print(-np.log(softmax_outputs[range(len(softmax_outputs)),class_targets]))
neg_log= -np.log(softmax_outputs[range(len(softmax_outputs)),class_targets])
average_loss=np.mean(neg_log)
print(average_loss)

[0.35667494 0.69314718 0.10536052]
0.38506088005216804
