In [1]:
import numpy as np

Neural Network Neuron Forward Pass with NumPy Dot Product
---
This code computes the output of a single neuron using NumPy’s dot function to perform the dot product between input values and their corresponding weights, then adds a bias term — demonstrating that the dot product is commutative for two 1D arrays, so both np.dot(weights, inputs) and np.dot(inputs, weights) yield the same result, producing a scalar output that represents the linear transformation of the neuron before activation.

In [11]:
import numpy as np
inputs=[1.0,2.0,3.0,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2.0
outputs=np.dot(weights,inputs)+bias
outputs1=np.dot(inputs,weights)+bias

print(outputs)
print(outputs1)

4.8
4.8


Dense Layer Forward Pass with NumPy Matrix Multiplication
---
This code computes the forward pass of a dense layer with three neurons and four inputs using NumPy’s matrix multiplication (np.dot), where the weight matrix is multiplied by the input vector to produce a batch of weighted sums, and the bias vector is added element-wise to generate the final output — resulting in a three-element vector that represents the linear transformation applied by each neuron in the layer before any activation function.

In [17]:
inputs=[1.0,2.0,3.0,2.5]
weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]
biases=[2.0,3.0,0.5]

layer_outputs=np.dot(weights , inputs)+biases
print(layer_outputs)

[4.8   1.21  2.385]


Batched Dense Layer Forward Pass with NumPy
---
This code performs a forward pass for a batch of three input samples through a dense layer with three neurons, using NumPy’s matrix multiplication to compute the dot product between each input vector and the transposed weight matrix, then adding the bias vector element-wise — producing a 3×3 output matrix where each row corresponds to the linear outputs of all neurons for one input sample, enabling efficient parallel evaluation across multiple data points. The np.array() conversion ensures that weights is explicitly treated as a NumPy array, guaranteeing proper matrix operations even if weights were initially defined as a nested Python list — this avoids potential ambiguity in broadcasting or alignment during np.dot, ensuring consistent and predictable behavior across different input types.

In [20]:
inputs=[[1.0,2.0,3.0,2.5],[2.0,5.0,-1.0,2.0],[-1.5,2.7,3.3,-0.8]]
weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]
biases=[2.0,3.0,0.5]

outputs=np.dot(inputs,np.array(weights).T)+biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
